name: Streamlyne Development Blog
company:
  name: Streamlyne Technologies Limited
  url: http://streamlyne.co
markdown: redcarpet
pygments: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

baseurl: /
permalink: /post/:title

authors:
  glavin:
    name: Glavin Wiechert
    gravatar: c66919cb194f96c696c1da0c47354a6a
    email: glavin@streamlyne.co
    url: http://www.linkedin.com/in/glavin
    twitter: GlavinW
    linkedin: http://www.linkedin.com/in/glavin
    github: Glavin001
    phone: (902)225-7035
  dawson:
    name: Dawson Reid
    gravatar: 12e480a364a5c19214f99b4dfe9a11d5
    email: dawson@streamlyne.co
    url: http://company.com
    twitter: DawsonReid
    linkedin: dawsonreid
    github: dreid93
  todd:
    name: Todd Murphy
    url: streamlyne.co
    email: todd@streamlyne.co
